global:
  host: 43.136.232.129
server:
  port: 10000
spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://${global.host}:3306/security_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysqlpwd
  redis:
    host: ${global.host}
    port: 6379
mybatis-plus:
  global-config:
    banner: off
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml